### ISSUE TITLE
header authorization

### ISSUE THREAD

**Issue by monxian** [AshikNesin/axios-fileupload#1]
Can't seem to get header authorization to work. 
Is there a way to insert the token into the const config?

`const request = axiosFileupload(`${ROOT_URL}/photos/upload/`+ id, data )`

**Comment by monxian** [comment]
fixed by adding a function param of my token
const request = axiosFileupload(${ROOT_URL}/photos/upload/+ id, data, token )

then in axios-fileupload index.js  const config added 'authorization':token.
 Hope this helps other noobs like me

**Comment by AshikNesin** [comment]
@monxian Thanks, Benny! Will add that in README soon.
